apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ tpl .Values.resource.default.name . }}-ingress
  labels:
    app: {{ tpl .Values.resource.default.name . }}
spec:
  rules:
  - host: chiaras-website.i07ip.k8s.gollum.westeurope.azure.gigantic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ tpl .Values.resource.default.name . }}-service
          servicePort: 80